<?php
/**
 * Created by PhpStorm.
 * User: Mikou
 * Date: 2018/9/8 0008
 * Time: 22:48
 */

namespace app\admin\controller;

use think\Controller;
use think\Db;
use think\Request;

class Tag extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $css = config('style_path.admin_css_path');
        $js = config('style_path.admin_js_path');
        $img = config('style_path.admin_img_path');
        $picture = config('style_path.admin_picture_path');
        $this->assign(array(
            'css' => $css,
            'js' => $js,
            'img' => $img,
            'picture' => $picture
        ));
    }

    public function index()
    {
        return view('admin@tag/index');
    }

    public function getTagList()
    {
        $list = Db::name('tag')->field('id,name,status')->select();
        $this->ajaxReturnMsg(200, 'success', $list);
    }

    public function addTag(Request $request)
    {
        $data = $request->post();
        if (!isset($data['name']) || empty($data['name'])) {
            $this->ajaxReturnMsg(201, '参数错误', '');
        }
        $param['name']= $data['name'];
        $param['status'] = 1;
        Db::name('tag')->insert($param);
        $this->ajaxReturnMsg(200, 'success', '');
    }


    public function banTag(Request $request)
    {
        $data = $request->post();
        if (!isset($data['id']) || empty($data['id'])) {
            $this->ajaxReturnMsg(201, '参数错误', '');
        }
        $param['status'] = 0;
        Db::name('tag')->where('id',$data['id'])->update($param);
        $this->ajaxReturnMsg(200, 'success', '');
    }

    public function openTag(Request $request)
    {
        $data = $request->post();
        if (!isset($data['id']) || empty($data['id'])) {
            $this->ajaxReturnMsg(201, '参数错误', '');
        }
        $param['status'] = 1;
        Db::name('tag')->where('id',$data['id'])->update($param);
        $this->ajaxReturnMsg(200, 'success', '');
    }


    private function ajaxReturnMsg($code = 200, $msg, $data, $api_id = 0)
    {
        //        $this->api->end($api_id,$code,$msg,$data);
        header('Access-Control-Allow-Origin: *');//跨域
        header('Content-type: application/json');
        echo json_encode(array('code' => $code, 'msg' => $msg, 'data' => $data));
        die;
    }

}